services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  timescaledb-data:
