# Stage 1: Build React App
FROM node:20-alpine as builder
WORKDIR /app/src/client

# Install dependencies specifically for the React app
COPY src/client/package*.json ./
RUN npm ci

# Copy the source code and build
COPY src/client ./
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/src/client/build /usr/share/nginx/html
EXPOSE 80
